FROM unity-sds/sounder_sips_pge_common:r0.1.0 AS builder

ARG BUILD_PATH /build
ARG NUM_COMPILE_JOBS=4

RUN cd $BUILD_PATH/spss/src/sips_pge/l1b_atms/make && make -j $NUM_COMPILE_JOBS

FROM centos:7

RUN mkdir -p /pge/bin
COPY --from=builder /build/spss/src/sips_pge/l1b_atms/main/bin/L1BMw_main /pge/bin

RUN yum install -y libquadmath && \
    yum clean all && \
    rm -rf /var/cache/yum

CMD ["/pge/bin/L1BMw_main"]
